apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 596212444151.dkr.ecr.eu-west-3.amazonaws.com/webinar-cicd:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080